const Routes = [
  { method: 'get', path: '/Cases/:caseId', controller: 'Case', action: 'GetCase' },
  { method: 'get', path: '/Cases/GetCount', controller: 'Case', action: 'GetCasescount' },
  { method: 'get', path: '/Cases/GetCompleteCase', controller: 'Case', action: 'GetCompleteCase' },
  { method: 'get', path: '/Cases/GetDeactivateCase', controller: 'Case', action: 'GetDeactivateCase' },
  { method: 'post', path: '/Cases/AddRecord', controller: 'Case', action: 'AddArrayCase' },
  { method: 'get', path: '/Cases', controller: 'Case', action: 'GetCases' },
  { method: 'post', path: '/Cases', controller: 'Case', action: 'AddCase' },
  { method: 'put', path: '/Cases', controller: 'Case', action: 'UpdateCase' },
  { method: 'delete', path: '/Cases/:caseId', controller: 'Case', action: 'DeleteCase' },

  { method: 'get', path: '/Courts/GetCount', controller: 'Court', action: 'GetCourtscount' },
  { method: 'get', path: '/Courts/:courtId', controller: 'Court', action: 'GetCourt' },
  { method: 'get', path: '/Courts', controller: 'Court', action: 'GetCourts' },
  { method: 'post', path: '/Courts/AddRecord', controller: 'Court', action: 'AddArrayCourt' },
  { method: 'post', path: '/Courts', controller: 'Court', action: 'AddCourt' },
  { method: 'put', path: '/Courts', controller: 'Court', action: 'UpdateCourt' },
  { method: 'delete', path: '/Courts/:courtId', controller: 'Court', action: 'DeleteCourt' },

  { method: 'get', path: '/Courthauses/GetCount', controller: 'Courthause', action: 'GetCourthausescount' },
  { method: 'get', path: '/Courthauses/:courthauseId', controller: 'Courthause', action: 'GetCourthause' },
  { method: 'get', path: '/Courthauses', controller: 'Courthause', action: 'GetCourthauses' },
  { method: 'post', path: '/Courthauses/AddRecord', controller: 'Courthause', action: 'AddArrayCourthause' },
  { method: 'post', path: '/Courthauses', controller: 'Courthause', action: 'AddCourthause' },
  { method: 'put', path: '/Courthauses', controller: 'Courthause', action: 'UpdateCourthause' },
  { method: 'delete', path: '/Courthauses/:courthauseId', controller: 'Courthause', action: 'DeleteCourthause' },

  { method: 'get', path: '/Definedcompanies/GetCount', controller: 'Definedcompany', action: 'GetDefinedcompaniescount' },
  { method: 'get', path: '/Definedcompanies/:definedcompanyId', controller: 'Definedcompany', action: 'GetDefinedcompany' },
  { method: 'get', path: '/Definedcompanies', controller: 'Definedcompany', action: 'GetDefinedcompanies' },
  { method: 'post', path: '/Definedcompanies/AddRecord', controller: 'Definedcompany', action: 'AddArrayDefinedcompany' },
  { method: 'post', path: '/Definedcompanies', controller: 'Definedcompany', action: 'AddDefinedcompany' },
  { method: 'put', path: '/Definedcompanies', controller: 'Definedcompany', action: 'UpdateDefinedcompany' },
  { method: 'delete', path: '/Definedcompanies/:definedcompanyId', controller: 'Definedcompany', action: 'DeleteDefinedcompany' },

  { method: 'get', path: '/Definedcostumers/GetCount', controller: 'Definedcostumer', action: 'GetDefinedcostumerscount' },
  { method: 'get', path: '/Definedcostumers/:definedcostumerId', controller: 'Definedcostumer', action: 'GetDefinedcostumer' },
  { method: 'get', path: '/Definedcostumers', controller: 'Definedcostumer', action: 'GetDefinedcostumers' },
  { method: 'post', path: '/Definedcostumers/AddRecord', controller: 'Definedcostumer', action: 'AddArrayDefinedcostumer' },
  { method: 'post', path: '/Definedcostumers', controller: 'Definedcostumer', action: 'AddDefinedcostumer' },
  { method: 'put', path: '/Definedcostumers', controller: 'Definedcostumer', action: 'UpdateDefinedcostumer' },
  { method: 'delete', path: '/Definedcostumers/:definedcostumerId', controller: 'Definedcostumer', action: 'DeleteDefinedcostumer' },

  { method: 'get', path: '/Documents/GetCount', controller: 'Document', action: 'GetDocumentscount' },
  { method: 'get', path: '/Documents/:documentId', controller: 'Document', action: 'GetDocument' },
  { method: 'get', path: '/Documents', controller: 'Document', action: 'GetDocuments' },
  { method: 'post', path: '/Documents/AddRecord', controller: 'Document', action: 'AddArrayDocument' },
  { method: 'post', path: '/Documents', controller: 'Document', action: 'AddDocument' },
  { method: 'put', path: '/Documents', controller: 'Document', action: 'UpdateDocument' },
  { method: 'delete', path: '/Documents/:documentId', controller: 'Document', action: 'DeleteDocument' },

  { method: 'get', path: '/Goals/GetCount', controller: 'Goal', action: 'GetGoalscount' },
  { method: 'get', path: '/Goals/:goalId', controller: 'Goal', action: 'GetGoal' },
  { method: 'get', path: '/Goals', controller: 'Goal', action: 'GetGoals' },
  { method: 'post', path: '/Goals/AddRecord', controller: 'Goal', action: 'AddArrayGoal' },
  { method: 'post', path: '/Goals', controller: 'Goal', action: 'AddGoal' },
  { method: 'put', path: '/Goals', controller: 'Goal', action: 'UpdateGoal' },
  { method: 'delete', path: '/Goals/:goalId', controller: 'Goal', action: 'DeleteGoal' },

  { method: 'get', path: '/Kdvs/GetCount', controller: 'Kdv', action: 'GetKdvscount' },
  { method: 'get', path: '/Kdvs/:kdvId', controller: 'Kdv', action: 'GetKdv' },
  { method: 'get', path: '/Kdvs', controller: 'Kdv', action: 'GetKdvs' },
  { method: 'post', path: '/Kdvs/AddRecord', controller: 'Kdv', action: 'AddArrayKdv' },
  { method: 'post', path: '/Kdvs', controller: 'Kdv', action: 'AddKdv' },
  { method: 'put', path: '/Kdvs', controller: 'Kdv', action: 'UpdateKdv' },
  { method: 'delete', path: '/Kdvs/:kdvId', controller: 'Kdv', action: 'DeleteKdv' },

  { method: 'get', path: '/Languages/GetCount', controller: 'Language', action: 'GetLanguagescount' },
  { method: 'get', path: '/Languages/Getconfig', controller: 'Language', action: 'GetLanguageconfig' },
  { method: 'post', path: '/Languages/Saveconfig', controller: 'Language', action: 'UpdateLanguageconfig' },
  { method: 'get', path: '/Languages/:languageId', controller: 'Language', action: 'GetLanguage' },
  { method: 'get', path: '/Languages', controller: 'Language', action: 'GetLanguages' },
  { method: 'post', path: '/Languages/AddRecord', controller: 'Language', action: 'AddArrayLanguage' },
  { method: 'post', path: '/Languages', controller: 'Language', action: 'AddLanguage' },
  { method: 'put', path: '/Languages', controller: 'Language', action: 'UpdateLanguage' },
  { method: 'delete', path: '/Languages/:languageId', controller: 'Language', action: 'DeleteLanguage' },

  { method: 'get', path: '/Recordtypes/GetCount', controller: 'Recordtype', action: 'GetRecordtypescount' },
  { method: 'get', path: '/Recordtypes/:recordtypeId', controller: 'Recordtype', action: 'GetRecordtype' },
  { method: 'get', path: '/Recordtypes', controller: 'Recordtype', action: 'GetRecordtypes' },
  { method: 'post', path: '/Recordtypes/AddRecord', controller: 'Recordtype', action: 'AddArrayRecordtype' },
  { method: 'post', path: '/Recordtypes', controller: 'Recordtype', action: 'AddRecordtype' },
  { method: 'put', path: '/Recordtypes', controller: 'Recordtype', action: 'UpdateRecordtype' },
  { method: 'delete', path: '/Recordtypes/:recordtypeId', controller: 'Recordtype', action: 'DeleteRecordtype' },

  { method: 'get', path: '/Translators/GetCount', controller: 'Translator', action: 'GetTranslatorscount' },
  { method: 'get', path: '/Translators/:translatorId', controller: 'Translator', action: 'GetTranslator' },
  { method: 'get', path: '/Translators', controller: 'Translator', action: 'GetTranslators' },
  { method: 'post', path: '/Translators/AddRecord', controller: 'Translator', action: 'AddArrayTranslator' },
  { method: 'post', path: '/Translators', controller: 'Translator', action: 'AddTranslator' },
  { method: 'put', path: '/Translators', controller: 'Translator', action: 'UpdateTranslator' },
  { method: 'delete', path: '/Translators/:translatorId', controller: 'Translator', action: 'DeleteTranslator' },

  { method: 'get', path: '/Payments/GetCount', controller: 'Payment', action: 'GetPaymentscount' },
  { method: 'get', path: '/Payments/:paymentId', controller: 'Payment', action: 'GetPayment' },
  { method: 'get', path: '/Payments', controller: 'Payment', action: 'GetPayments' },
  { method: 'post', path: '/Payments/AddRecord', controller: 'Payment', action: 'AddArrayPayment' },
  { method: 'post', path: '/Payments', controller: 'Payment', action: 'AddPayment' },
  { method: 'put', path: '/Payments', controller: 'Payment', action: 'UpdatePayment' },
  { method: 'delete', path: '/Payments/:paymentId', controller: 'Payment', action: 'DeletePayment' },

]

module.exports = Routes